name: PR Build

on: [ pull_request ]

jobs:
  init:
    name: Init
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup build scan capture
        uses: gradle/github-actions/maven-build-scan-setup@v0.2.1
        with:
          wrapper-init: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven 1
        run: ./mvnw clean
      - name: Build with Maven 2
        run: ./mvnw foo

  build:
    name: Build
    if: ${{ always() && !cancelled() }}
    needs: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup build scan capture
        uses: gradle/github-actions/maven-build-scan-setup@v0.2.1
        with:
          wrapper-init: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven 1
        run: ./mvnw clean
      - name: Build with Maven 2
        run: ./mvnw foo

#  test-matrix:
#    name: test-matrix
#    if: ${{ always() && !cancelled() }}
#    strategy:
#      matrix:
#        version: [ "1.17.4", "1.17.3", "1.17.2" ]
#    needs: Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Setup build scan capture
#        uses: gradle/github-actions/maven-build-scan-setup@v0.2.1
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#      - name: Replace GE version
#        run: |
#          sed -i 's/1.18.1/${{ matrix.version}}/g' .mvn/extensions.xml
#          cat .mvn/extensions.xml
#          scanCount=$(find ./scan-maven-*/ -type f -name 'scan.scan' | wc -l)
#      - name: Build with Maven 1
#        run: mvn clean
#      - name: Build with Maven 2
#        run: mvn foo
