name: "Gradle Enterprise TOS"
on:
    issue_comment:
        types: [ created ]
    pull_request_target:
        types: [ opened,closed,synchronize ]

permissions:
    actions: write
    contents: write
    pull-requests: write
    statuses: write

jobs:
    GE-TOS:
        runs-on: ubuntu-latest
        steps:
            -   name: "Gradle Enterprise TOS"
                uses: actions/build-scan-tos@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
