name: Gradle - Terms of Service approval verification

on:
  issue_comment:
    types: [ created ]
  pull_request_target:

jobs:
  gradle-check-tos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    steps:
      - name: Gradle - Terms of Service approval verification
        uses: gradle/github-actions/tos-check/run@v0.1
        with:
          tos-location: 'https://foo.bar/tos.html'
