name: Gradle - Terms of Service approval verification

on:
  issue_comment:
    types: [ created ]
  pull_request_target:

jobs:
  run-terms-of-service-acceptance:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Gradle - Terms of Service approval verification
        uses: gradle/github-actions/terms-of-service-acceptance/run@v0.2
        with:
          tos-location: 'https://foo.bar/tos.html'
          white-list: jprinet-jfrog,foo,jprinet,bar
          white-list-only: true
